In [1]:
dataset_folder = '/home/erwin/Downloads/ml-100k'

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = dataset_folder + '/u.data'

In [4]:
columns = ['userId', 'movieId', 'rating', 't']
df = pd.read_csv(data, names=columns, sep='\t')

In [5]:
df.head()

userId  movieId  rating          t
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [6]:
df['userId'].value_counts()

405    737
655    685
13     636
450    540
276    518
      ... 
147     20
19      20
572     20
636     20
895     20
Name: userId, Length: 943, dtype: int64

In [7]:
df['movieId'].value_counts()

50      583
258     509
100     508
181     507
294     485
       ... 
1648      1
1571      1
1329      1
1457      1
1663      1
Name: movieId, Length: 1682, dtype: int64

In [8]:
df['rating'].value_counts()

4    34174
3    27145
5    21201
2    11370
1     6110
Name: rating, dtype: int64

In [9]:
movie = dataset_folder + '/u.item'

In [10]:
df_movie = pd.read_csv(movie, sep='\|')

/home/erwin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [11]:
df_movie

1                                   Toy Story (1995)  01-Jan-1995  \
0        2                                   GoldenEye (1995)  01-Jan-1995   
1        3                                  Four Rooms (1995)  01-Jan-1995   
2        4                                  Get Shorty (1995)  01-Jan-1995   
3        5                                     Copycat (1995)  01-Jan-1995   
4        6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...  01-Jan-1995   
...    ...                                                ...          ...   
1676  1678                                  Mat' i syn (1997)  06-Feb-1998   
1677  1679                                   B. Monkey (1998)  06-Feb-1998   
1678  1680                               Sliding Doors (1998)  01-Jan-1998   
1679  1681                                You So Crazy (1994)  01-Jan-1994   
1680  1682          Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      Unnamed: 3 http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)  0  \
0            NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...     0   
1            NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...     0   
2            NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...     0   
3            NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)     0   
4            NaN  http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...     0   
...          ...                                                ...    ..   
1676         NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...     0   
1677         NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...     0   
1678         NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)     0   
1679         NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...     0   
1680         NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...     0   

      0.1  0.2  1.1  1.2  ...  0.6  0.7  0.8  0.9  0.10  0.11  0.12  0.13  \
0       1    1    0    0  ...    0    0    0    0     0     0     0     1   
1       0    0    0    0  ...    0    0    0    0     0     0     0     1   
2       1    0    0    0  ...    0    0    0    0     0     0     0     0   
3       0    0    0    0  ...    0    0    0    0     0     0     0     1   
4       0    0    0    0  ...    0    0    0    0     0     0     0     0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   
1676    0    0    0    0  ...    0    0    0    0     0     0     0     0   
1677    0    0    0    0  ...    0    0    0    0     0     1     0     1   
1678    0    0    0    0  ...    0    0    0    0     0     1     0     0   
1679    0    0    0    0  ...    0    0    0    0     0     0     0     0   
1680    0    0    0    0  ...    0    0    0    0     0     0     0     0   

      0.14  0.15  
0        0     0  
1        0     0  
2        0     0  
3        0     0  
4        0     0  
...    ...   ...  
1676     0     0  
1677     0     0  
1678     0     0  
1679     0     0  
1680     0     0  

[1681 rows x 24 columns]

In [12]:
df_filtered = df[['userId', 'movieId', 'rating']]

In [13]:
df_filtered.head()

userId  movieId  rating
0     196      242       3
1     186      302       3
2      22      377       1
3     244       51       2
4     166      346       1

In [14]:
k = 20

In [15]:
sparsity = 100000 / (1682 * 943)

In [16]:
sparsity

0.06304669364224531

In [17]:
R = np.zeros((943, 1682))

In [18]:
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
for row in df_filtered.values:
#     print(row)
    R[ row[0]-1, row[1]-1 ] = row[2]

In [20]:
max(df['movieId'])

1682

In [21]:
min(df['movieId'])

1

In [22]:
R

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [23]:
# X = np.random.rand(943,k)
# Y = np.random.rand(1682,k)
X = np.ones((943,k))
Y = np.ones((1682,k))

In [24]:
X.shape[0]

943

In [25]:
epochs = 1000

In [26]:
def ALS_v1(R, epochs=10, _lambda=0.1):
    # X = np.random.rand(943,k)
    # Y = np.random.rand(1682,k)
    X = np.ones((943,k))
    Y = np.ones((1682,k))
    
    for _ in range(epochs):
        # Xu^T = Ru . Y(Y^TY + lambda*Ik)^(-1) -> ruas kanan = (1,1682) . (1682,k) . (k,k) = 1,k
        # Ru = R[u,:]
        precompute_Y = np.matmul(Y, (np.linalg.inv( np.matmul(Y.T, Y) + (_lambda * np.eye(Y.shape[1])) )))
        for u in range(X.shape[0]):
            X[u,:] = np.matmul(R[u,:], precompute_Y)

        # Yi^T = Ri . X(X^TX + lambda*Ik)^(-1) -> ruas kanan = (1,943) . (943,k) . (k,k) = 1,k
        # Ri = R[:,i]
        precompute_X = np.matmul(X, (np.linalg.inv( np.matmul(X.T, X) + (_lambda * np.eye(Y.shape[1])) )))
        for i in range(Y.shape[0]):
            Y[i,:] = np.matmul(R[:,i], precompute_X)
        
    return X, Y

In [27]:
def ALS_v2(R, epochs=10, _lambda=0.1):
    # X = np.random.rand(943,k)
    # Y = np.random.rand(1682,k)
    X = np.ones((k,943))
    Y = np.ones((k,1682))
    
    for _ in range(epochs):
        # U = X, V = Y
        # U=(VVT+λI)^(−1).V.RT
        X = np.matmul( np.matmul( np.linalg.inv(np.matmul(Y, Y.T) + (_lambda * np.eye(Y.shape[0]))) ,Y) , R.T)
        Y = np.matmul( np.matmul( np.linalg.inv(np.matmul(X, X.T) + (_lambda * np.eye(X.shape[0]))) ,X) , R)
        
    return X.T, Y.T

In [28]:
X1, Y1 = ALS_v1(R, epochs=100)

In [44]:
X2, Y2 = ALS_v2(R, epochs=100)

In [30]:
X1

array([[-0.62888129,  0.04622367, -0.40837492, ...,  0.215538  ,
        -0.11122853,  1.36109903],
       [ 1.67566865, -0.25736797,  0.7877733 , ..., -0.58073214,
         1.33365658,  0.4126542 ],
       [ 0.03695677,  0.34771164,  0.37734722, ..., -1.05836945,
         0.95836859,  0.32877092],
       ...,
       [ 0.60338153, -0.32602861,  0.44380638, ..., -0.48928238,
         0.3665849 ,  0.5313463 ],
       [ 0.28951234, -0.17208016,  0.30800259, ...,  0.31327668,
         0.96206157, -0.2945754 ],
       [-0.94847765,  0.40925931, -0.06780741, ...,  0.30588118,
        -1.44637894, -0.23151667]])

In [31]:
Y1

array([[ 5.27238249e+00,  7.02539712e-01,  1.89732108e+00, ...,
         2.33597548e+00,  2.27359402e+00,  3.68447484e+00],
       [ 2.19910166e+00,  9.10521505e-01,  5.18658057e-01, ...,
         1.27615235e+00,  8.52659561e-01,  1.43209013e+00],
       [ 6.95502538e-01,  1.31975712e-01,  7.25286995e-01, ...,
         1.46142932e-01,  2.36119182e-01,  6.67376791e-01],
       ...,
       [-7.83916366e-03, -6.07638612e-03, -1.15168284e-03, ...,
        -2.43819343e-03,  1.10664438e-02,  6.57305880e-03],
       [ 2.12838812e-02, -1.32899901e-05,  1.19623839e-02, ...,
         4.61279888e-03,  2.63159594e-02, -2.83372420e-04],
       [-3.15327349e-02,  1.19867600e-02,  3.75807615e-02, ...,
         8.33264440e-04,  8.08899304e-04,  4.65006639e-03]])

In [32]:
np.dot(X1[0,:], Y1[0,:])

4.004893923702938

In [33]:
R[0,0]

5.0

In [45]:
X2

array([[ 0.99978272, -1.42504711,  0.72524613, ..., -0.76319072,
         1.15768675, -0.39905341],
       [-1.46876613,  0.35854473,  0.1233039 , ...,  1.73867564,
         1.01392611, -0.87520949],
       [-0.34642847, -0.1039357 , -0.61695673, ...,  1.29766264,
         0.43918922, -0.09056269],
       ...,
       [-0.79090614, -0.04040614, -0.03837863, ...,  0.16214273,
         0.42556117,  0.36097415],
       [-0.68411797,  0.84591001,  0.27283549, ...,  1.46760637,
        -0.14433996,  0.82501748],
       [ 0.92029312, -0.25316253, -1.43160762, ..., -1.71330337,
        -1.06238367,  0.34370235]])

In [46]:
Y2

array([[ 1.96859149e+00,  3.31869362e+00,  2.64059316e+00, ...,
         3.10387381e+00,  3.21142358e+00,  2.97659026e+00],
       [ 1.23679876e+00,  1.52587604e+00,  8.70115770e-01, ...,
         1.33659242e+00,  4.89999745e-01,  8.08903770e-01],
       [ 2.69319628e-01,  4.33497983e-01,  9.08039153e-01, ...,
         2.12914596e-01,  6.77654617e-01,  6.18298393e-01],
       ...,
       [-1.71719914e-03,  3.60514735e-03,  2.84821993e-03, ...,
        -1.00447065e-03,  2.19041928e-03,  5.50084002e-03],
       [ 2.16127717e-02,  3.07501609e-02,  1.61141798e-02, ...,
         2.86167937e-02, -6.94401828e-03, -2.26363061e-04],
       [ 3.10817396e-03, -1.92484350e-03,  2.22280661e-02, ...,
        -1.52936337e-03,  2.94917684e-02,  1.01664024e-02]])

In [47]:
np.dot(X2[0,:], Y2[0,:])

4.000867405632302

In [37]:
R1 = np.matmul(X1, Y1.T)

In [38]:
R1

array([[ 4.00489392e+00,  2.09971253e+00,  1.37264317e+00, ...,
        -3.84056555e-03,  2.62896077e-02,  7.33308327e-02],
       [ 1.98936884e+00, -2.09204745e-02, -4.69196534e-03, ...,
         9.28223688e-03, -2.66729697e-03, -2.94588208e-02],
       [-1.75890007e-01, -5.61772097e-02,  1.80497693e-01, ...,
         2.16326607e-02,  1.89999608e-03,  2.00743038e-04],
       ...,
       [ 2.23120754e+00,  3.75971074e-02,  2.76000861e-01, ...,
        -5.51582355e-03,  1.06521206e-02, -4.20623069e-03],
       [ 1.30268561e+00,  1.52101883e-01, -4.76609785e-01, ...,
         1.50266816e-02,  1.14518680e-02, -2.94552835e-02],
       [ 1.70921256e+00,  2.04716259e+00,  1.17928321e+00, ...,
        -9.90463051e-03,  1.73748658e-02,  2.05664464e-02]])

In [48]:
R2 = np.matmul(X2, Y2.T)

In [49]:
R2

array([[ 4.00086741e+00,  2.09817445e+00,  1.37399060e+00, ...,
        -3.78011985e-03,  2.63031353e-02,  7.34691997e-02],
       [ 1.98856773e+00, -2.10028454e-02, -4.92384406e-03, ...,
         9.27331834e-03, -2.67938786e-03, -2.94858661e-02],
       [-1.74942692e-01, -5.53220220e-02,  1.80760140e-01, ...,
         2.16303492e-02,  1.89926232e-03,  2.41687606e-04],
       ...,
       [ 2.23179156e+00,  3.71148605e-02,  2.75408280e-01, ...,
        -5.51621570e-03,  1.06594824e-02, -4.29622053e-03],
       [ 1.30409020e+00,  1.52537224e-01, -4.76178638e-01, ...,
         1.50309947e-02,  1.14582359e-02, -2.94495805e-02],
       [ 1.71279623e+00,  2.04978179e+00,  1.18054401e+00, ...,
        -9.89222550e-03,  1.73578345e-02,  2.06545320e-02]])

## Get Recommendation

input = (prediction ratings, user id, top n reco)

In [67]:
def get_reco(original_R, predicted_R, user_id, top_n=10):
    if user_id > 942:
        return []
    
    result = []
    predicted_ratings = predicted_R[user_id, :]
    result = list(zip(predicted_ratings, [i for i in range(len(predicted_ratings))]))
    result.sort(key=lambda x: (-x[0]))
    
    filtered = [x for x in result if original_R[user_id, x[1]] == 0]
    return [x[1] for x in filtered[:top_n]]

In [68]:
get_reco(R, R2, 0)

1682


[99, 49, 167, 173, 152, 88, 143, 172, 175, 227]

In [60]:
get_reco(R, R1, 100)

[120, 404, 116, 117, 741, 0, 236, 124, 596, 180]

In [65]:
print(R[0,:])

[5. 3. 4. ... 0. 0. 0.]
